name: AdriftHardcore
version: ${project.version}
main: me.itsadrift.adrifthardcore.AdriftHardcore
api-version: 1.18
depend: [TAB]
commands:
  adrifthardcore:
    aliases: [hardcore, hc, ahc, ah]
  life:
    aliases: [lifes, lives, live]
